name: Run bowtie random tests for all commits to master on Ubuntu and MacOS
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - 'bowtie'
      - 'bowtie-build'
      - 'bowtie-inspect'
      - 'Makefile'
      - 'scripts/test/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - 'bowtie'
      - 'bowtie-build'
      - 'bowtie-inspect'
      - 'Makefile'
      - 'scripts/test/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install zlib development files
        run: |
          sudo apt-get update
          sudo apt-get install zlib1g-dev
  linux:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Run random tests
        run: |
          make allall
          make random-test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run random tests
        run: |
          make allall
          make random-test
